### ISSUE TITLE
Amazon Elasticache Compatible? 

### ISSUE THREAD

**Issue by deanrad** [meteor/redis-livedata#17]
We have an app which works against a manually installed Redis, but when we point it to Elasticache in AWS we get:

```
20150414-16:54:25.679(-5)? (STDERR)
W20150414-16:54:25.680(-5)? (STDERR) /Users/dradcliffe/.meteor/packages/meteor-tool/.1.1.1.46baqh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20150414-16:54:25.680(-5)? (STDERR)                        throw(ex);
W20150414-16:54:25.680(-5)? (STDERR)                              ^
W20150414-16:54:25.681(-5)? (STDERR) Error: ERR unknown command 'config'
W20150414-16:54:25.681(-5)? (STDERR)     at Object.Future.wait (/Users/dradcliffe/.meteor/packages/meteor-tool/.1.1.1.46baqh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:395:16)
W20150414-16:54:25.681(-5)? (STDERR)     at [object Object]._.extend.get (packages/slava:redis-livedata/sync_map.js:45:1)
W20150414-16:54:25.681(-5)? (STDERR)     at new Meteor.RedisCollection (packages/slava:redis-livedata/redis_collection.js:23:1)
```

Any insight to what this error means ? Has this package been tested against elasticache ? 

Reproduction steps: 
- Provision Elasticache in AWS
- Start a meteor app using this package, but with REDIS_URL pointing to the Elasticache instance above.

**Comment by zzsnzmn** [comment]
We've determined the cause of this issue--- AWS elasticache disallows the use of the CONFIG Redis command.

Even if you've configured keyspace notification properly it appears that by just calling `connection.config('get', ...)`. I propose an extra setting `SKIP_CONFIG_CHECK` or something along those lines as it will allow users who have already set up redis properly to still connect. If `SKIP_CONFIG_CHECK` is set to true/1 log a warning saying so.
